approve:
- commandHelpLink: ""
  repos:
  - openshift-assisted/assisted-installer-deployment
  require_self_approval: false
lgtm:
- repos:
  - openshift-assisted/assisted-installer-deployment
  review_acts_as_lgtm: true
plugins:
  openshift-assisted/assisted-installer-deployment:
    plugins:
    - assign
    - blunderbuss
    - bugzilla
    - cat
    - dog
    - heart
    - golint
    - goose
    - help
    - hold
    - jira
    - label
    - lgtm
    - lifecycle
    - override
    - pony
    - retitle
    - shrug
    - sigmention
    - skip
    - trigger
    - verify-owners
    - owners-label
    - wip
    - yuks
    - approve
